# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The client-serving radio frequencies. ('Dual band operation', '5 GHz band
  # only' or 'Dual band operation with Band Steering')
  class BandSelectionEnum
    BAND_SELECTION_ENUM = [
      # TODO: Write general description for ENUM_DUAL_BAND_OPERATION
      ENUM_DUAL_BAND_OPERATION = 'Dual band operation'.freeze,

      # TODO: Write general description for ENUM_5_GHZ_BAND_ONLY
      ENUM_5_GHZ_BAND_ONLY = '5 GHz band only'.freeze,

      # TODO: Write general description for
      # ENUM_DUAL_BAND_OPERATION_WITH_BAND_STEERING
      ENUM_DUAL_BAND_OPERATION_WITH_BAND_STEERING = 'Dual band operation with Band Steering'.freeze
    ].freeze
  end
end
