# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # BlinkLedsNetworkDeviceModel Model.
  class BlinkLedsNetworkDeviceModel < BaseModel
    # The duration in seconds. Must be between 5 and 120. Default is 20 seconds
    # @return [Integer]
    attr_accessor :duration

    # The period in milliseconds. Must be between 100 and 1000. Default is 160
    # milliseconds
    # @return [Integer]
    attr_accessor :period

    # The duty cycle as the percent active. Must be between 10 and 90. Default
    # is 50.
    # @return [Integer]
    attr_accessor :duty

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['duration'] = 'duration'
      @_hash['period'] = 'period'
      @_hash['duty'] = 'duty'
      @_hash
    end

    def initialize(duration = nil,
                   period = nil,
                   duty = nil,
                   additional_properties = {})
      @duration = duration
      @period = period
      @duty = duty

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      duration = hash['duration']
      period = hash['period']
      duty = hash['duty']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      BlinkLedsNetworkDeviceModel.new(duration,
                                      period,
                                      duty,
                                      hash)
    end
  end
end
