# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateOrganizationActionBatchModel Model.
  class CreateOrganizationActionBatchModel < BaseModel
    # Set to true for immediate execution. Set to false if the action should be
    # previewed before executing.
    # @return [String]
    attr_accessor :confirmed

    # Force the batch to run synchronous. There can be at most 20 actions in
    # synchronous batch.
    # @return [String]
    attr_accessor :synchronous

    # A set of changes to make as part of this action (<a
    # href='https://developer.cisco.com/meraki/api/#/rest/guides/action-batches/
    # '>more details</a>)
    # @return [List of ActionModel]
    attr_accessor :actions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['confirmed'] = 'confirmed'
      @_hash['synchronous'] = 'synchronous'
      @_hash['actions'] = 'actions'
      @_hash
    end

    def initialize(confirmed = nil,
                   synchronous = nil,
                   actions = nil)
      @confirmed = confirmed
      @synchronous = synchronous
      @actions = actions
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      confirmed = hash['confirmed']
      synchronous = hash['synchronous']
      # Parameter is an array, so we need to iterate through it
      actions = nil
      unless hash['actions'].nil?
        actions = []
        hash['actions'].each do |structure|
          actions << (ActionModel.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      CreateOrganizationActionBatchModel.new(confirmed,
                                             synchronous,
                                             actions)
    end
  end
end
