# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateNetworkSwitchStacksModel Model.
  class CreateNetworkSwitchStacksModel < BaseModel
    # The name of the new stack
    # @return [String]
    attr_accessor :name

    # An array of switch serials to be added into the new stack
    # @return [List of String]
    attr_accessor :serials

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['serials'] = 'serials'
      @_hash
    end

    def initialize(name = nil,
                   serials = nil,
                   additional_properties = {})
      @name = name
      @serials = serials

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      serials = hash['serials']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      CreateNetworkSwitchStacksModel.new(name,
                                         serials,
                                         hash)
    end
  end
end
