# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateNetworkSmProfileUmbrellaModel Model.
  class CreateNetworkSmProfileUmbrellaModel < BaseModel
    # The name to be given to the new profile
    # @return [String]
    attr_accessor :name

    # The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll)
    # and a set of tags of the devices to be assigned
    # @return [String]
    attr_accessor :scope

    # The bundle ID of the application, defaults to com.cisco.ciscosecurity.app
    # @return [String]
    attr_accessor :app_bundle_identifier

    # The bundle ID of the provider, defaults to
    # com.cisco.ciscosecurity.app.CiscoUmbrella
    # @return [String]
    attr_accessor :provider_bundle_identifier

    # The specific ProviderConfiguration to be passed to the filtering
    # framework, as JSON. ProviderConfiguration should be an array of objects,
    # as:
    # [ { "key": "some_key", type: "some_type", "value": "some_value" }, ... ]
    # type is one of manual_string, manual_int, manual_boolean, manual_choice,
    # manual_multiselect, manual_list,
    # auto_username, auto_email, auto_mac_address, auto_serial_number,
    # auto_notes, auto_name
    # @return [String]
    attr_accessor :provider_configuration

    # Whether the certificate should be attached to this profile (one of true,
    # false).
    # @return [String]
    attr_accessor :uses_cert

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['scope'] = 'scope'
      @_hash['app_bundle_identifier'] = 'AppBundleIdentifier'
      @_hash['provider_bundle_identifier'] = 'ProviderBundleIdentifier'
      @_hash['provider_configuration'] = 'ProviderConfiguration'
      @_hash['uses_cert'] = 'usesCert'
      @_hash
    end

    def initialize(name = nil,
                   scope = nil,
                   app_bundle_identifier = nil,
                   provider_bundle_identifier = nil,
                   provider_configuration = nil,
                   uses_cert = nil)
      @name = name
      @scope = scope
      @app_bundle_identifier = app_bundle_identifier
      @provider_bundle_identifier = provider_bundle_identifier
      @provider_configuration = provider_configuration
      @uses_cert = uses_cert
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      scope = hash['scope']
      app_bundle_identifier = hash['AppBundleIdentifier']
      provider_bundle_identifier = hash['ProviderBundleIdentifier']
      provider_configuration = hash['ProviderConfiguration']
      uses_cert = hash['usesCert']

      # Create object from extracted values.
      CreateNetworkSmProfileUmbrellaModel.new(name,
                                              scope,
                                              app_bundle_identifier,
                                              provider_bundle_identifier,
                                              provider_configuration,
                                              uses_cert)
    end
  end
end
