# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateNetworkGroupPoliciesModel Model.
  class CreateNetworkGroupPoliciesModel < BaseModel
    # The name for your group policy. Required.
    # @return [String]
    attr_accessor :name

    # The schedule for the group policy. Schedules are applied to days of the
    # week.
    # @return [SchedulingModel]
    attr_accessor :scheduling

    # The bandwidth settings for clients bound to your group policy.
    # @return [BandwidthModel]
    attr_accessor :bandwidth

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['scheduling'] = 'scheduling'
      @_hash['bandwidth'] = 'bandwidth'
      @_hash
    end

    def initialize(name = nil,
                   scheduling = nil,
                   bandwidth = nil,
                   additional_properties = {})
      @name = name
      @scheduling = scheduling
      @bandwidth = bandwidth

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      scheduling = SchedulingModel.from_hash(hash['scheduling']) if
        hash['scheduling']
      bandwidth = BandwidthModel.from_hash(hash['bandwidth']) if
        hash['bandwidth']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      CreateNetworkGroupPoliciesModel.new(name,
                                          scheduling,
                                          bandwidth,
                                          hash)
    end
  end
end
