# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateNetworkStaticRoutesModel Model.
  class CreateNetworkStaticRoutesModel < BaseModel
    # The name of the new static route
    # @return [String]
    attr_accessor :name

    # The subnet of the static route
    # @return [String]
    attr_accessor :subnet

    # The gateway IP (next hop) of the static route
    # @return [String]
    attr_accessor :gateway_ip

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['subnet'] = 'subnet'
      @_hash['gateway_ip'] = 'gatewayIp'
      @_hash
    end

    def initialize(name = nil,
                   subnet = nil,
                   gateway_ip = nil,
                   additional_properties = {})
      @name = name
      @subnet = subnet
      @gateway_ip = gateway_ip

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      subnet = hash['subnet']
      gateway_ip = hash['gatewayIp']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      CreateNetworkStaticRoutesModel.new(name,
                                         subnet,
                                         gateway_ip,
                                         hash)
    end
  end
end
