# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # CreateNetworkHttpServersModel Model.
  class CreateNetworkHttpServersModel < BaseModel
    # A name for easy reference to the HTTP server
    # @return [String]
    attr_accessor :name

    # The URL of the HTTP server
    # @return [String]
    attr_accessor :url

    # A shared secret that will be included in POSTs sent to the HTTP server.
    # This secret can be used to verify that the request was sent by Meraki.
    # @return [String]
    attr_accessor :shared_secret

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['url'] = 'url'
      @_hash['shared_secret'] = 'sharedSecret'
      @_hash
    end

    def initialize(name = nil,
                   url = nil,
                   shared_secret = nil,
                   additional_properties = {})
      @name = name
      @url = url
      @shared_secret = shared_secret

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      url = hash['url']
      shared_secret = hash['sharedSecret']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      CreateNetworkHttpServersModel.new(name,
                                        url,
                                        shared_secret,
                                        hash)
    end
  end
end
