# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The client IP assignment mode ('NAT mode', 'Bridge mode', 'Layer 3 roaming',
  # 'Layer 3 roaming with a concentrator' or 'VPN')
  class IpAssignmentModeEnum
    IP_ASSIGNMENT_MODE_ENUM = [
      # TODO: Write general description for ENUM_NAT_MODE
      ENUM_NAT_MODE = 'NAT mode'.freeze,

      # TODO: Write general description for ENUM_BRIDGE_MODE
      ENUM_BRIDGE_MODE = 'Bridge mode'.freeze,

      # TODO: Write general description for ENUM_LAYER_3_ROAMING
      ENUM_LAYER_3_ROAMING = 'Layer 3 roaming'.freeze,

      # TODO: Write general description for
      # ENUM_LAYER_3_ROAMING_WITH_A_CONCENTRATOR
      ENUM_LAYER_3_ROAMING_WITH_A_CONCENTRATOR = 'Layer 3 roaming with a concentrator'.freeze,

      # TODO: Write general description for VPN
      VPN = 'VPN'.freeze
    ].freeze
  end
end
