# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # 'Deny' traffic specified by this rule
  class PolicyEnum
    POLICY_ENUM = [
      # TODO: Write general description for DENY
      DENY = 'deny'.freeze
    ].freeze
  end
end
