# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The policy applied to matching traffic. Must be 'deny'.
  class Policy1Enum
    POLICY1_ENUM = [
      # TODO: Write general description for DENY
      DENY = 'deny'.freeze
    ].freeze
  end
end
