# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Per switch exception (combined, redundant, useNetworkSetting)
  class PowerTypeEnum
    POWER_TYPE_ENUM = [
      # TODO: Write general description for COMBINED
      COMBINED = 'combined'.freeze,

      # TODO: Write general description for REDUNDANT
      REDUNDANT = 'redundant'.freeze,

      # TODO: Write general description for USENETWORKSETTING
      USENETWORKSETTING = 'useNetworkSetting'.freeze
    ].freeze
  end
end
