# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # PowerExceptionModel Model.
  class PowerExceptionModel < BaseModel
    # Serial number of the switch
    # @return [String]
    attr_accessor :serial

    # Per switch exception (combined, redundant, useNetworkSetting)
    # @return [String]
    attr_accessor :power_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['serial'] = 'serial'
      @_hash['power_type'] = 'powerType'
      @_hash
    end

    def initialize(serial = nil,
                   power_type = nil,
                   additional_properties = {})
      @serial = serial
      @power_type = power_type

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      serial = hash['serial']
      power_type = hash['powerType']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      PowerExceptionModel.new(serial,
                              power_type,
                              hash)
    end
  end
end
