# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # RadiusServerModel Model.
  class RadiusServerModel < BaseModel
    # IP address of your RADIUS server
    # @return [String]
    attr_accessor :host

    # UDP port the RADIUS server listens on for Access-requests
    # @return [String]
    attr_accessor :port

    # RADIUS client shared secret
    # @return [String]
    attr_accessor :secret

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['host'] = 'host'
      @_hash['port'] = 'port'
      @_hash['secret'] = 'secret'
      @_hash
    end

    def initialize(host = nil,
                   port = nil,
                   secret = nil,
                   additional_properties = {})
      @host = host
      @port = port
      @secret = secret

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      host = hash['host']
      port = hash['port']
      secret = hash['secret']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      RadiusServerModel.new(host,
                            port,
                            secret,
                            hash)
    end
  end
end
