# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Rule3Model Model.
  class Rule3Model < BaseModel
    # Description of the rule (optional)
    # @return [String]
    attr_accessor :comment

    # 'Allow' or 'Deny' traffic specified by this rule
    # @return [String]
    attr_accessor :policy

    # The type of protocol (must be 'tcp', 'udp', 'icmp' or 'any')
    # @return [String]
    attr_accessor :protocol

    # Comma-separated list of source port(s) (integer in the range 1-65535), or
    # 'any'
    # @return [String]
    attr_accessor :src_port

    # Comma-separated list of source IP address(es) (in IP or CIDR notation), or
    # 'any' (FQDN not supported)
    # @return [String]
    attr_accessor :src_cidr

    # Comma-separated list of destination port(s) (integer in the range
    # 1-65535), or 'any'
    # @return [String]
    attr_accessor :dest_port

    # Comma-separated list of destination IP address(es) (in IP or CIDR
    # notation) or 'any' (FQDN not supported)
    # @return [String]
    attr_accessor :dest_cidr

    # Log this rule to syslog (true or false, boolean value) - only applicable
    # if a syslog has been configured (optional)
    # @return [Boolean]
    attr_accessor :syslog_enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['comment'] = 'comment'
      @_hash['policy'] = 'policy'
      @_hash['protocol'] = 'protocol'
      @_hash['src_port'] = 'srcPort'
      @_hash['src_cidr'] = 'srcCidr'
      @_hash['dest_port'] = 'destPort'
      @_hash['dest_cidr'] = 'destCidr'
      @_hash['syslog_enabled'] = 'syslogEnabled'
      @_hash
    end

    def initialize(policy = nil,
                   protocol = nil,
                   src_cidr = nil,
                   dest_cidr = nil,
                   comment = nil,
                   src_port = nil,
                   dest_port = nil,
                   syslog_enabled = nil,
                   additional_properties = {})
      @comment = comment
      @policy = policy
      @protocol = protocol
      @src_port = src_port
      @src_cidr = src_cidr
      @dest_port = dest_port
      @dest_cidr = dest_cidr
      @syslog_enabled = syslog_enabled

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      policy = hash['policy']
      protocol = hash['protocol']
      src_cidr = hash['srcCidr']
      dest_cidr = hash['destCidr']
      comment = hash['comment']
      src_port = hash['srcPort']
      dest_port = hash['destPort']
      syslog_enabled = hash['syslogEnabled']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      Rule3Model.new(policy,
                     protocol,
                     src_cidr,
                     dest_cidr,
                     comment,
                     src_port,
                     dest_port,
                     syslog_enabled,
                     hash)
    end
  end
end
