# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Rule2Model Model.
  class Rule2Model < BaseModel
    # 'Deny' traffic specified by this rule
    # @return [PolicyEnum]
    attr_accessor :policy

    # Type of the L7 rule. One of: 'application', 'applicationCategory', 'host',
    # 'port', 'ipRange'
    # @return [TypeEnum]
    attr_accessor :type

    # The 'value' of what you want to block. Format of 'value' varies depending
    # on type of the rule. See sample request. The application categories and
    # application ids can be retrieved from the the 'MX L7 application
    # categories' endpoint. The countries follow the two-letter ISO 3166-1
    # alpha-2 format.
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['policy'] = 'policy'
      @_hash['type'] = 'type'
      @_hash['value'] = 'value'
      @_hash
    end

    def initialize(policy = nil,
                   type = nil,
                   value = nil,
                   additional_properties = {})
      @policy = policy
      @type = type
      @value = value

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      policy = hash['policy']
      type = hash['type']
      value = hash['value']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      Rule2Model.new(policy,
                     type,
                     value,
                     hash)
    end
  end
end
