# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # ServerModel Model.
  class ServerModel < BaseModel
    # The IP address of the syslog server
    # @return [String]
    attr_accessor :host

    # The port of the syslog server
    # @return [Integer]
    attr_accessor :port

    # A list of roles for the syslog server. Options (case-insensitive):
    # 'Wireless event log', 'Appliance event log', 'Switch event log', 'Air
    # Marshal events', 'Flows', 'URLs', 'IDS alerts', 'Security events'
    # @return [List of String]
    attr_accessor :roles

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['host'] = 'host'
      @_hash['port'] = 'port'
      @_hash['roles'] = 'roles'
      @_hash
    end

    def initialize(host = nil,
                   port = nil,
                   roles = nil,
                   additional_properties = {})
      @host = host
      @port = port
      @roles = roles

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      host = hash['host']
      port = hash['port']
      roles = hash['roles']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      ServerModel.new(host,
                      port,
                      roles,
                      hash)
    end
  end
end
