# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # How Bonjour rules are applied. Can be 'network default', 'ignore' or
  # 'custom'.
  class Settings3Enum
    SETTINGS3_ENUM = [
      # TODO: Write general description for ENUM_NETWORK_DEFAULT
      ENUM_NETWORK_DEFAULT = 'network default'.freeze,

      # TODO: Write general description for IGNORE
      IGNORE = 'ignore'.freeze,

      # TODO: Write general description for CUSTOM
      CUSTOM = 'custom'.freeze
    ].freeze
  end
end
