# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # SnapshotNetworkCameraModel Model.
  class SnapshotNetworkCameraModel < BaseModel
    # [optional] The snapshot will be taken from this time on the camera. The
    # timestamp is expected to be in ISO 8601 format. If no timestamp is
    # specified, we will assume current time.
    # @return [String]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    def initialize(timestamp = nil,
                   additional_properties = {})
      @timestamp = timestamp

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      timestamp = hash['timestamp']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      SnapshotNetworkCameraModel.new(timestamp,
                                     hash)
    end
  end
end
