# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The type of splash page for the SSID ('None', 'Click-through splash page',
  # 'Billing', 'Password-protected with Meraki RADIUS', 'Password-protected with
  # custom RADIUS', 'Password-protected with Active Directory',
  # 'Password-protected with LDAP', 'SMS authentication', 'Systems Manager
  # Sentry', 'Facebook Wi-Fi', 'Google OAuth' or 'Sponsored guest'). This
  # attribute is not supported for template children.
  class SplashPageEnum
    SPLASH_PAGE_ENUM = [
      # TODO: Write general description for NONE
      NONE = 'None'.freeze,

      # TODO: Write general description for ENUM_CLICKTHROUGH_SPLASH_PAGE
      ENUM_CLICKTHROUGH_SPLASH_PAGE = 'Click-through splash page'.freeze,

      # TODO: Write general description for BILLING
      BILLING = 'Billing'.freeze,

      # TODO: Write general description for
      # ENUM_PASSWORDPROTECTED_WITH_MERAKI_RADIUS
      ENUM_PASSWORDPROTECTED_WITH_MERAKI_RADIUS = 'Password-protected with Meraki RADIUS'.freeze,

      # TODO: Write general description for
      # ENUM_PASSWORDPROTECTED_WITH_CUSTOM_RADIUS
      ENUM_PASSWORDPROTECTED_WITH_CUSTOM_RADIUS = 'Password-protected with custom RADIUS'.freeze,

      # TODO: Write general description for
      # ENUM_PASSWORDPROTECTED_WITH_ACTIVE_DIRECTORY
      ENUM_PASSWORDPROTECTED_WITH_ACTIVE_DIRECTORY = 'Password-protected with Active Directory'.freeze,

      # TODO: Write general description for ENUM_PASSWORDPROTECTED_WITH_LDAP
      ENUM_PASSWORDPROTECTED_WITH_LDAP = 'Password-protected with LDAP'.freeze,

      # TODO: Write general description for ENUM_SMS_AUTHENTICATION
      ENUM_SMS_AUTHENTICATION = 'SMS authentication'.freeze,

      # TODO: Write general description for ENUM_SYSTEMS_MANAGER_SENTRY
      ENUM_SYSTEMS_MANAGER_SENTRY = 'Systems Manager Sentry'.freeze,

      # TODO: Write general description for ENUM_FACEBOOK_WIFI
      ENUM_FACEBOOK_WIFI = 'Facebook Wi-Fi'.freeze,

      # TODO: Write general description for ENUM_GOOGLE_OAUTH
      ENUM_GOOGLE_OAUTH = 'Google OAuth'.freeze,

      # TODO: Write general description for ENUM_SPONSORED_GUEST
      ENUM_SPONSORED_GUEST = 'Sponsored guest'.freeze
    ].freeze
  end
end
