# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The target SSIDs. For each SSID where isAuthorized is true, the expiration
  # time will automatically be set according to the SSID's splash frequency.
  class SsidsModel < BaseModel
    # New authorization status for SSID (true, false).
    # @return [String]
    attr_accessor :is_authorized

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['is_authorized'] = 'isAuthorized'
      @_hash
    end

    def initialize(is_authorized = nil,
                   additional_properties = {})
      @is_authorized = is_authorized

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      is_authorized = hash['isAuthorized']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      SsidsModel.new(is_authorized,
                     hash)
    end
  end
end
