# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Tag2Model Model.
  class Tag2Model < BaseModel
    # The name of the tag
    # @return [String]
    attr_accessor :tag

    # The privilege of the SAML administrator on the tag
    # @return [String]
    attr_accessor :access

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tag'] = 'tag'
      @_hash['access'] = 'access'
      @_hash
    end

    def initialize(tag = nil,
                   access = nil,
                   additional_properties = {})
      @tag = tag
      @access = access

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      tag = hash['tag']
      access = hash['access']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      Tag2Model.new(tag,
                    access,
                    hash)
    end
  end
end
