# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The type of definition. Can be one of 'application', 'applicationCategory',
  # 'host', 'port', 'ipRange' or 'localNet'.
  class Type1Enum
    TYPE1_ENUM = [
      # TODO: Write general description for APPLICATION
      APPLICATION = 'application'.freeze,

      # TODO: Write general description for APPLICATIONCATEGORY
      APPLICATIONCATEGORY = 'applicationCategory'.freeze,

      # TODO: Write general description for HOST
      HOST = 'host'.freeze,

      # TODO: Write general description for PORT
      PORT = 'port'.freeze,

      # TODO: Write general description for IPRANGE
      IPRANGE = 'ipRange'.freeze,

      # TODO: Write general description for LOCALNET
      LOCALNET = 'localNet'.freeze
    ].freeze
  end
end
