# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Type of the L7 rule. One of: 'application', 'applicationCategory', 'host',
  # 'port', 'ipRange'
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for APPLICATION
      APPLICATION = 'application'.freeze,

      # TODO: Write general description for APPLICATIONCATEGORY
      APPLICATIONCATEGORY = 'applicationCategory'.freeze,

      # TODO: Write general description for HOST
      HOST = 'host'.freeze,

      # TODO: Write general description for PORT
      PORT = 'port'.freeze,

      # TODO: Write general description for IPRANGE
      IPRANGE = 'ipRange'.freeze
    ].freeze
  end
end
