# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkClientPolicyModel Model.
  class UpdateNetworkClientPolicyModel < BaseModel
    # The group policy (Whitelisted, Blocked, Normal, Group policy)
    # @return [String]
    attr_accessor :device_policy

    # [optional] If devicePolicy param is set to 'Group policy' this param is
    # used to specify the group ID.
    # @return [String]
    attr_accessor :group_policy_id

    # The timespan for which clients will be fetched. Must be in seconds and
    # less than or equal to a month (2592000 seconds).
    # @return [String]
    attr_accessor :timespan

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_policy'] = 'devicePolicy'
      @_hash['group_policy_id'] = 'groupPolicyId'
      @_hash['timespan'] = 'timespan'
      @_hash
    end

    def initialize(device_policy = nil,
                   group_policy_id = nil,
                   timespan = nil,
                   additional_properties = {})
      @device_policy = device_policy
      @group_policy_id = group_policy_id
      @timespan = timespan

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_policy = hash['devicePolicy']
      group_policy_id = hash['groupPolicyId']
      timespan = hash['timespan']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkClientPolicyModel.new(device_policy,
                                         group_policy_id,
                                         timespan,
                                         hash)
    end
  end
end
