# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkSmDeviceFieldsModel Model.
  class UpdateNetworkSmDeviceFieldsModel < BaseModel
    # The wifiMac of the device to be modified.
    # @return [String]
    attr_accessor :wifi_mac

    # The id of the device to be modified.
    # @return [String]
    attr_accessor :id

    # The serial of the device to be modified.
    # @return [String]
    attr_accessor :serial

    # The new fields of the device. Passed in as a JSON object. The list of
    # available fields are: name, notes
    # @return [Object]
    attr_accessor :device_fields

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['wifi_mac'] = 'wifiMac'
      @_hash['id'] = 'id'
      @_hash['serial'] = 'serial'
      @_hash['device_fields'] = 'deviceFields'
      @_hash
    end

    def initialize(wifi_mac = nil,
                   id = nil,
                   serial = nil,
                   device_fields = nil,
                   additional_properties = {})
      @wifi_mac = wifi_mac
      @id = id
      @serial = serial
      @device_fields = device_fields

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      wifi_mac = hash['wifiMac']
      id = hash['id']
      serial = hash['serial']
      device_fields = hash['deviceFields']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkSmDeviceFieldsModel.new(wifi_mac,
                                           id,
                                           serial,
                                           device_fields,
                                           hash)
    end
  end
end
