# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateOrganizationVpnFirewallRulesModel Model.
  class UpdateOrganizationVpnFirewallRulesModel < BaseModel
    # An ordered array of the firewall rules (not including the default rule)
    # @return [List of Rule3Model]
    attr_accessor :rules

    # Log the special default rule (boolean value - enable only if you've
    # configured a syslog server) (optional)
    # @return [Boolean]
    attr_accessor :syslog_default_rule

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['rules'] = 'rules'
      @_hash['syslog_default_rule'] = 'syslogDefaultRule'
      @_hash
    end

    def initialize(rules = nil,
                   syslog_default_rule = nil,
                   additional_properties = {})
      @rules = rules
      @syslog_default_rule = syslog_default_rule

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      rules = nil
      unless hash['rules'].nil?
        rules = []
        hash['rules'].each do |structure|
          rules << (Rule3Model.from_hash(structure) if structure)
        end
      end
      syslog_default_rule = hash['syslogDefaultRule']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateOrganizationVpnFirewallRulesModel.new(rules,
                                                  syslog_default_rule,
                                                  hash)
    end
  end
end
