# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateDeviceSwitchPortModel Model.
  class UpdateDeviceSwitchPortModel < BaseModel
    # The name of the switch port
    # @return [String]
    attr_accessor :name

    # The tags of the switch port
    # @return [String]
    attr_accessor :tags

    # The status of the switch port
    # @return [String]
    attr_accessor :enabled

    # The type of the switch port ("access" or "trunk")
    # @return [String]
    attr_accessor :type

    # The VLAN of the switch port
    # @return [String]
    attr_accessor :vlan

    # The voice VLAN of the switch port. Only applicable to access ports.
    # @return [String]
    attr_accessor :voice_vlan

    # The VLANs allowed on the switch port. Only applicable to trunk ports.
    # @return [String]
    attr_accessor :allowed_vlans

    # The PoE status of the switch port
    # @return [String]
    attr_accessor :poe_enabled

    # The isolation status of the switch port
    # @return [String]
    attr_accessor :isolation_enabled

    # The rapid spanning tree protocol status
    # @return [String]
    attr_accessor :rstp_enabled

    # The state of the STP guard ("disabled", "Root guard", "BPDU guard", "Loop
    # guard")
    # @return [String]
    attr_accessor :stp_guard

    # The number of the access policy of the switch port. Only applicable to
    # access ports.
    # @return [String]
    attr_accessor :access_policy_number

    # The link speed for the switch port
    # @return [String]
    attr_accessor :link_negotiation

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['tags'] = 'tags'
      @_hash['enabled'] = 'enabled'
      @_hash['type'] = 'type'
      @_hash['vlan'] = 'vlan'
      @_hash['voice_vlan'] = 'voiceVlan'
      @_hash['allowed_vlans'] = 'allowedVlans'
      @_hash['poe_enabled'] = 'poeEnabled'
      @_hash['isolation_enabled'] = 'isolationEnabled'
      @_hash['rstp_enabled'] = 'rstpEnabled'
      @_hash['stp_guard'] = 'stpGuard'
      @_hash['access_policy_number'] = 'accessPolicyNumber'
      @_hash['link_negotiation'] = 'linkNegotiation'
      @_hash
    end

    def initialize(name = nil,
                   tags = nil,
                   enabled = nil,
                   type = nil,
                   vlan = nil,
                   voice_vlan = nil,
                   allowed_vlans = nil,
                   poe_enabled = nil,
                   isolation_enabled = nil,
                   rstp_enabled = nil,
                   stp_guard = nil,
                   access_policy_number = nil,
                   link_negotiation = nil)
      @name = name
      @tags = tags
      @enabled = enabled
      @type = type
      @vlan = vlan
      @voice_vlan = voice_vlan
      @allowed_vlans = allowed_vlans
      @poe_enabled = poe_enabled
      @isolation_enabled = isolation_enabled
      @rstp_enabled = rstp_enabled
      @stp_guard = stp_guard
      @access_policy_number = access_policy_number
      @link_negotiation = link_negotiation
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      tags = hash['tags']
      enabled = hash['enabled']
      type = hash['type']
      vlan = hash['vlan']
      voice_vlan = hash['voiceVlan']
      allowed_vlans = hash['allowedVlans']
      poe_enabled = hash['poeEnabled']
      isolation_enabled = hash['isolationEnabled']
      rstp_enabled = hash['rstpEnabled']
      stp_guard = hash['stpGuard']
      access_policy_number = hash['accessPolicyNumber']
      link_negotiation = hash['linkNegotiation']

      # Create object from extracted values.
      UpdateDeviceSwitchPortModel.new(name,
                                      tags,
                                      enabled,
                                      type,
                                      vlan,
                                      voice_vlan,
                                      allowed_vlans,
                                      poe_enabled,
                                      isolation_enabled,
                                      rstp_enabled,
                                      stp_guard,
                                      access_policy_number,
                                      link_negotiation)
    end
  end
end
