# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateOrganizationThirdPartyVPNPeersModel Model.
  class UpdateOrganizationThirdPartyVPNPeersModel < BaseModel
    # The list of VPN peers
    # @return [List of PeerModel]
    attr_accessor :peers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['peers'] = 'peers'
      @_hash
    end

    def initialize(peers = nil,
                   additional_properties = {})
      @peers = peers

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      peers = nil
      unless hash['peers'].nil?
        peers = []
        hash['peers'].each do |structure|
          peers << (PeerModel.from_hash(structure) if structure)
        end
      end

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateOrganizationThirdPartyVPNPeersModel.new(peers,
                                                    hash)
    end
  end
end
