# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkSmDevicesTagsModel Model.
  class UpdateNetworkSmDevicesTagsModel < BaseModel
    # The wifiMacs of the devices to be modified.
    # @return [String]
    attr_accessor :wifi_macs

    # The ids of the devices to be modified.
    # @return [String]
    attr_accessor :ids

    # The serials of the devices to be modified.
    # @return [String]
    attr_accessor :serials

    # The scope (one of all, none, withAny, withAll, withoutAny, or withoutAll)
    # and a set of tags of the devices to be modified.
    # @return [String]
    attr_accessor :scope

    # The tags to be added, deleted, or updated.
    # @return [String]
    attr_accessor :tags

    # One of add, delete, or update. Only devices that have been modified will
    # be returned.
    # @return [String]
    attr_accessor :update_action

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['wifi_macs'] = 'wifiMacs'
      @_hash['ids'] = 'ids'
      @_hash['serials'] = 'serials'
      @_hash['scope'] = 'scope'
      @_hash['tags'] = 'tags'
      @_hash['update_action'] = 'updateAction'
      @_hash
    end

    def initialize(wifi_macs = nil,
                   ids = nil,
                   serials = nil,
                   scope = nil,
                   tags = nil,
                   update_action = nil,
                   additional_properties = {})
      @wifi_macs = wifi_macs
      @ids = ids
      @serials = serials
      @scope = scope
      @tags = tags
      @update_action = update_action

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      wifi_macs = hash['wifiMacs']
      ids = hash['ids']
      serials = hash['serials']
      scope = hash['scope']
      tags = hash['tags']
      update_action = hash['updateAction']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkSmDevicesTagsModel.new(wifi_macs,
                                          ids,
                                          serials,
                                          scope,
                                          tags,
                                          update_action,
                                          hash)
    end
  end
end
