# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkSmTargetGroupModel Model.
  class UpdateNetworkSmTargetGroupModel < BaseModel
    # The name of this target group
    # @return [String]
    attr_accessor :name

    # The scope and tag options of the target group. Comma separated values
    # beginning with one of withAny, withAll, withoutAny, withoutAll, all, none,
    # followed by tags
    # @return [String]
    attr_accessor :scope

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['scope'] = 'scope'
      @_hash
    end

    def initialize(name = nil,
                   scope = nil,
                   additional_properties = {})
      @name = name
      @scope = scope

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      scope = hash['scope']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkSmTargetGroupModel.new(name,
                                          scope,
                                          hash)
    end
  end
end
