# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkClientSplashAuthorizationStatusModel Model.
  class UpdateNetworkClientSplashAuthorizationStatusModel < BaseModel
    # The target SSIDs. For each SSID where isAuthorized is true, the expiration
    # time will automatically be set according to the SSID's splash frequency.
    # @return [SsidsModel]
    attr_accessor :ssids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ssids'] = 'ssids'
      @_hash
    end

    def initialize(ssids = nil,
                   additional_properties = {})
      @ssids = ssids

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ssids = SsidsModel.from_hash(hash['ssids']) if hash['ssids']

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkClientSplashAuthorizationStatusModel.new(ssids,
                                                            hash)
    end
  end
end
