# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # UpdateNetworkUplinkSettingsModel Model.
  class UpdateNetworkUplinkSettingsModel < BaseModel
    # A mapping of uplinks ('wan1', 'wan2' or 'cellular') to their bandwidth
    # settings (be sure to check which uplinks are supported for your network).
    # Bandwidth setting objects have the following structure
    # @return [BandwidthLimits2Model]
    attr_accessor :bandwidth_limits

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bandwidth_limits'] = 'bandwidthLimits'
      @_hash
    end

    def initialize(bandwidth_limits = nil,
                   additional_properties = {})
      @bandwidth_limits = bandwidth_limits

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      if hash['bandwidthLimits']
        bandwidth_limits = BandwidthLimits2Model.from_hash(hash['bandwidthLimits'])
      end

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      UpdateNetworkUplinkSettingsModel.new(bandwidth_limits,
                                           hash)
    end
  end
end
