# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # Enable or disable the interface (only for MX devices). Valid values are
  # 'enabled', 'disabled', and 'not configured'.
  class WanEnabledEnum
    WAN_ENABLED_ENUM = [
      # TODO: Write general description for ENABLED
      ENABLED = 'enabled'.freeze,

      # TODO: Write general description for DISABLED
      DISABLED = 'disabled'.freeze,

      # TODO: Write general description for ENUM_NOT_CONFIGURED
      ENUM_NOT_CONFIGURED = 'not configured'.freeze
    ].freeze
  end
end
