# meraki
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Meraki
  # The types of WPA encryption. ('WPA1 and WPA2' or 'WPA2 only')
  class WpaEncryptionModeEnum
    WPA_ENCRYPTION_MODE_ENUM = [
      # TODO: Write general description for ENUM_WPA1_AND_WPA2
      ENUM_WPA1_AND_WPA2 = 'WPA1 and WPA2'.freeze,

      # TODO: Write general description for ENUM_WPA2_ONLY
      ENUM_WPA2_ONLY = 'WPA2 only'.freeze
    ].freeze
  end
end
