# meraki
#
# This file was automatically generated for meraki by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'meraki/api_helper.rb'
require_relative 'meraki/meraki_client.rb'

# Http
require_relative 'meraki/http/http_call_back.rb'
require_relative 'meraki/http/http_client.rb'
require_relative 'meraki/http/http_method_enum.rb'
require_relative 'meraki/http/http_request.rb'
require_relative 'meraki/http/http_response.rb'
require_relative 'meraki/http/http_context.rb'
require_relative 'meraki/http/faraday_client.rb'
require_relative 'meraki/http/auth/custom_header_auth.rb'

# Models
require_relative 'meraki/models/base_model.rb'
require_relative 'meraki/models/update_device_switch_port_model.rb'
require_relative 'meraki/models/update_network_model.rb'
require_relative 'meraki/models/update_network_alert_settings_model.rb'
require_relative 'meraki/models/default_destinations_model.rb'
require_relative 'meraki/models/alert_model.rb'
require_relative 'meraki/models/update_network_appliance_port_model.rb'
require_relative 'meraki/models/bind_network_model.rb'
require_relative 'meraki/models/update_network_bluetooth_settings_model.rb'
require_relative 'meraki/models/generate_network_camera_snapshot_model.rb'
require_relative 'meraki/models/update_network_cellular_firewall_rules_model.rb'
require_relative 'meraki/models/rule_model.rb'
require_relative 'meraki/models/provision_network_clients_model.rb'
require_relative 'meraki/models/update_network_client_policy_model.rb'
require_relative 'meraki/models/update_network_client_splash_authorization' \
                 '_status_model.rb'
require_relative 'meraki/models/ssids_model.rb'
require_relative 'meraki/models/update_network_content_filtering_model.rb'
require_relative 'meraki/models/claim_network_devices_model.rb'
require_relative 'meraki/models/update_network_device_model.rb'
require_relative 'meraki/models/blink_network_device_leds_model.rb'
require_relative 'meraki/models/update_network_device_management_interface' \
                 '_settings_model.rb'
require_relative 'meraki/models/wan1_model.rb'
require_relative 'meraki/models/wan2_model.rb'
require_relative 'meraki/models/update_network_device_wireless_radio_settings' \
                 '_model.rb'
require_relative 'meraki/models/update_network_firewalled_service_model.rb'
require_relative 'meraki/models/create_network_group_policy_model.rb'
require_relative 'meraki/models/scheduling_model.rb'
require_relative 'meraki/models/monday_model.rb'
require_relative 'meraki/models/tuesday_model.rb'
require_relative 'meraki/models/wednesday_model.rb'
require_relative 'meraki/models/thursday_model.rb'
require_relative 'meraki/models/friday_model.rb'
require_relative 'meraki/models/saturday_model.rb'
require_relative 'meraki/models/sunday_model.rb'
require_relative 'meraki/models/bandwidth_model.rb'
require_relative 'meraki/models/bandwidth_limits_model.rb'
require_relative 'meraki/models/firewall_and_traffic_shaping_model.rb'
require_relative 'meraki/models/traffic_shaping_rule_model.rb'
require_relative 'meraki/models/definition_model.rb'
require_relative 'meraki/models/per_client_bandwidth_limits_model.rb'
require_relative 'meraki/models/bandwidth_limits1_model.rb'
require_relative 'meraki/models/l3_firewall_rule_model.rb'
require_relative 'meraki/models/l7_firewall_rule_model.rb'
require_relative 'meraki/models/content_filtering_model.rb'
require_relative 'meraki/models/allowed_url_patterns_model.rb'
require_relative 'meraki/models/blocked_url_patterns_model.rb'
require_relative 'meraki/models/blocked_url_categories_model.rb'
require_relative 'meraki/models/vlan_tagging_model.rb'
require_relative 'meraki/models/bonjour_forwarding_model.rb'
require_relative 'meraki/models/rule1_model.rb'
require_relative 'meraki/models/update_network_group_policy_model.rb'
require_relative 'meraki/models/create_network_http_server_model.rb'
require_relative 'meraki/models/create_network_http_servers_webhook_test' \
                 '_model.rb'
require_relative 'meraki/models/update_network_http_server_model.rb'
require_relative 'meraki/models/update_network_l3_firewall_rules_model.rb'
require_relative 'meraki/models/update_network_l7_firewall_rules_model.rb'
require_relative 'meraki/models/rule4_model.rb'
require_relative 'meraki/models/update_network_netflow_settings_model.rb'
require_relative 'meraki/models/update_network_one_to_many_nat_rules_model.rb'
require_relative 'meraki/models/rule5_model.rb'
require_relative 'meraki/models/update_network_one_to_one_nat_rules_model.rb'
require_relative 'meraki/models/rule6_model.rb'
require_relative 'meraki/models/create_network_pii_request_model.rb'
require_relative 'meraki/models/update_network_port_forwarding_rules_model.rb'
require_relative 'meraki/models/rule7_model.rb'
require_relative 'meraki/models/update_network_security_intrusion_settings' \
                 '_model.rb'
require_relative 'meraki/models/protected_networks_model.rb'
require_relative 'meraki/models/update_network_security_malware_settings' \
                 '_model.rb'
require_relative 'meraki/models/allowed_url_model.rb'
require_relative 'meraki/models/allowed_file_model.rb'
require_relative 'meraki/models/update_network_site_to_site_vpn_model.rb'
require_relative 'meraki/models/hub_model.rb'
require_relative 'meraki/models/subnet_model.rb'
require_relative 'meraki/models/create_network_sm_app_polaris_model.rb'
require_relative 'meraki/models/update_network_sm_app_polaris_model.rb'
require_relative 'meraki/models/create_network_sm_bypass_activation_lock' \
                 '_attempt_model.rb'
require_relative 'meraki/models/update_network_sm_device_fields_model.rb'
require_relative 'meraki/models/device_fields_model.rb'
require_relative 'meraki/models/wipe_network_sm_device_model.rb'
require_relative 'meraki/models/checkin_network_sm_devices_model.rb'
require_relative 'meraki/models/move_network_sm_devices_model.rb'
require_relative 'meraki/models/update_network_sm_devices_tags_model.rb'
require_relative 'meraki/models/create_network_sm_profile_clarity_model.rb'
require_relative 'meraki/models/vendor_config_model.rb'
require_relative 'meraki/models/update_network_sm_profile_clarity_model.rb'
require_relative 'meraki/models/add_network_sm_profile_clarity_model.rb'
require_relative 'meraki/models/create_network_sm_profile_umbrella_model.rb'
require_relative 'meraki/models/provider_configuration_model.rb'
require_relative 'meraki/models/update_network_sm_profile_umbrella_model.rb'
require_relative 'meraki/models/add_network_sm_profile_umbrella_model.rb'
require_relative 'meraki/models/create_network_sm_target_group_model.rb'
require_relative 'meraki/models/update_network_sm_target_group_model.rb'
require_relative 'meraki/models/update_network_snmp_settings_model.rb'
require_relative 'meraki/models/user_model.rb'
require_relative 'meraki/models/update_network_ssid_model.rb'
require_relative 'meraki/models/radius_server_model.rb'
require_relative 'meraki/models/radius_accounting_server_model.rb'
require_relative 'meraki/models/ap_tags_and_vlan_id_model.rb'
require_relative 'meraki/models/update_network_ssid_l3_firewall_rules_model.rb'
require_relative 'meraki/models/rule8_model.rb'
require_relative 'meraki/models/update_network_ssids_plash_settings_model.rb'
require_relative 'meraki/models/update_network_ssid_traffic_shaping_model.rb'
require_relative 'meraki/models/rule9_model.rb'
require_relative 'meraki/models/create_network_static_route_model.rb'
require_relative 'meraki/models/update_network_static_route_model.rb'
require_relative 'meraki/models/create_network_switch_port_schedule_model.rb'
require_relative 'meraki/models/port_schedule_model.rb'
require_relative 'meraki/models/update_network_switch_port_schedule_model.rb'
require_relative 'meraki/models/update_network_switch_settings_model.rb'
require_relative 'meraki/models/power_exception_model.rb'
require_relative 'meraki/models/create_network_switch_settings_qos_rule' \
                 '_model.rb'
require_relative 'meraki/models/update_network_switch_settings_qos_rules' \
                 '_order_model.rb'
require_relative 'meraki/models/update_network_switch_settings_qos_rule' \
                 '_model.rb'
require_relative 'meraki/models/create_network_switch_stack_model.rb'
require_relative 'meraki/models/add_network_switch_stack_model.rb'
require_relative 'meraki/models/remove_network_switch_stack_model.rb'
require_relative 'meraki/models/update_network_syslog_servers_model.rb'
require_relative 'meraki/models/server_model.rb'
require_relative 'meraki/models/update_network_traffic_analysis_settings' \
                 '_model.rb'
require_relative 'meraki/models/custom_pie_chart_item_model.rb'
require_relative 'meraki/models/update_network_traffic_shaping_model.rb'
require_relative 'meraki/models/rule10_model.rb'
require_relative 'meraki/models/update_network_uplink_settings_model.rb'
require_relative 'meraki/models/bandwidth_limits6_model.rb'
require_relative 'meraki/models/wan11_model.rb'
require_relative 'meraki/models/wan21_model.rb'
require_relative 'meraki/models/cellular_model.rb'
require_relative 'meraki/models/create_network_vlan_model.rb'
require_relative 'meraki/models/update_network_vlan_model.rb'
require_relative 'meraki/models/reserved_ip_range_model.rb'
require_relative 'meraki/models/dhcp_option_model.rb'
require_relative 'meraki/models/update_network_vlans_enabled_state_model.rb'
require_relative 'meraki/models/update_network_warm_spare_settings_model.rb'
require_relative 'meraki/models/create_network_wireless_rf_profile_model.rb'
require_relative 'meraki/models/ap_band_settings_model.rb'
require_relative 'meraki/models/two_four_ghz_settings_model.rb'
require_relative 'meraki/models/five_ghz_settings_model.rb'
require_relative 'meraki/models/update_network_wireless_rf_profile_model.rb'
require_relative 'meraki/models/ap_band_settings1_model.rb'
require_relative 'meraki/models/two_four_ghz_settings1_model.rb'
require_relative 'meraki/models/five_ghz_settings1_model.rb'
require_relative 'meraki/models/lock_network_sm_devices_model.rb'
require_relative 'meraki/models/create_organization_model.rb'
require_relative 'meraki/models/update_organization_model.rb'
require_relative 'meraki/models/create_organization_action_batch_model.rb'
require_relative 'meraki/models/action_model.rb'
require_relative 'meraki/models/update_organization_action_batch_model.rb'
require_relative 'meraki/models/create_organization_admin_model.rb'
require_relative 'meraki/models/tag_model.rb'
require_relative 'meraki/models/network_model.rb'
require_relative 'meraki/models/update_organization_admin_model.rb'
require_relative 'meraki/models/create_organization_branding_policy_model.rb'
require_relative 'meraki/models/admin_settings_model.rb'
require_relative 'meraki/models/help_settings_model.rb'
require_relative 'meraki/models/update_organization_branding_policies' \
                 '_priorities_model.rb'
require_relative 'meraki/models/update_organization_branding_policy_model.rb'
require_relative 'meraki/models/help_settings1_model.rb'
require_relative 'meraki/models/claim_organization_model.rb'
require_relative 'meraki/models/license_model.rb'
require_relative 'meraki/models/clone_organization_model.rb'
require_relative 'meraki/models/create_organization_network_model.rb'
require_relative 'meraki/models/combine_organization_networks_model.rb'
require_relative 'meraki/models/create_organization_saml_role_model.rb'
require_relative 'meraki/models/tag2_model.rb'
require_relative 'meraki/models/network2_model.rb'
require_relative 'meraki/models/update_organization_saml_role_model.rb'
require_relative 'meraki/models/update_organization_security_intrusion' \
                 '_settings_model.rb'
require_relative 'meraki/models/whitelisted_rule_model.rb'
require_relative 'meraki/models/update_organization_snmp_model.rb'
require_relative 'meraki/models/update_organization_third_party_vpn_peers' \
                 '_model.rb'
require_relative 'meraki/models/peer_model.rb'
require_relative 'meraki/models/ipsec_policies_model.rb'
require_relative 'meraki/models/update_organization_vpn_firewall_rules_model.rb'
require_relative 'meraki/models/rule11_model.rb'
require_relative 'meraki/models/object_type_enum.rb'
require_relative 'meraki/models/udld_enum.rb'
require_relative 'meraki/models/major_minor_assignment_mode_enum.rb'
require_relative 'meraki/models/policy_enum.rb'
require_relative 'meraki/models/protocol_enum.rb'
require_relative 'meraki/models/uplink_enum.rb'
require_relative 'meraki/models/wan_enabled_enum.rb'
require_relative 'meraki/models/access_enum.rb'
require_relative 'meraki/models/settings_enum.rb'
require_relative 'meraki/models/settings1_enum.rb'
require_relative 'meraki/models/type_enum.rb'
require_relative 'meraki/models/policy1_enum.rb'
require_relative 'meraki/models/type1_enum.rb'
require_relative 'meraki/models/settings2_enum.rb'
require_relative 'meraki/models/settings4_enum.rb'
require_relative 'meraki/models/splash_auth_settings_enum.rb'
require_relative 'meraki/models/settings5_enum.rb'
require_relative 'meraki/models/settings6_enum.rb'
require_relative 'meraki/models/service_enum.rb'
require_relative 'meraki/models/policy4_enum.rb'
require_relative 'meraki/models/type4_enum.rb'
require_relative 'meraki/models/type5_enum.rb'
require_relative 'meraki/models/mode_enum.rb'
require_relative 'meraki/models/access1_enum.rb'
require_relative 'meraki/models/ssid_number_enum.rb'
require_relative 'meraki/models/auth_mode_enum.rb'
require_relative 'meraki/models/enterprise_admin_access_enum.rb'
require_relative 'meraki/models/encryption_mode_enum.rb'
require_relative 'meraki/models/wpa_encryption_mode_enum.rb'
require_relative 'meraki/models/splash_page_enum.rb'
require_relative 'meraki/models/radius_failover_policy_enum.rb'
require_relative 'meraki/models/radius_load_balancing_policy_enum.rb'
require_relative 'meraki/models/power_type_enum.rb'
require_relative 'meraki/models/protocol3_enum.rb'
require_relative 'meraki/models/protocol4_enum.rb'
require_relative 'meraki/models/mode1_enum.rb'
require_relative 'meraki/models/type7_enum.rb'
require_relative 'meraki/models/dhcp_handling_enum.rb'
require_relative 'meraki/models/dhcp_lease_time_enum.rb'
require_relative 'meraki/models/type9_enum.rb'
require_relative 'meraki/models/min_bitrate_type_enum.rb'
require_relative 'meraki/models/band_selection_type_enum.rb'
require_relative 'meraki/models/band_operation_mode_enum.rb'
require_relative 'meraki/models/min_bitrate_type1_enum.rb'
require_relative 'meraki/models/band_selection_type1_enum.rb'
require_relative 'meraki/models/band_operation_mode1_enum.rb'
require_relative 'meraki/models/org_access_enum.rb'
require_relative 'meraki/models/applies_to_enum.rb'
require_relative 'meraki/models/help_tab_enum.rb'
require_relative 'meraki/models/get_help_subtab_enum.rb'
require_relative 'meraki/models/community_subtab_enum.rb'
require_relative 'meraki/models/cases_subtab_enum.rb'
require_relative 'meraki/models/data_protection_requests_subtab_enum.rb'
require_relative 'meraki/models/universal_search_knowledge_base_search_enum.rb'
require_relative 'meraki/models/new_features_subtab_enum.rb'
require_relative 'meraki/models/firewall_info_subtab_enum.rb'
require_relative 'meraki/models/api_docs_subtab_enum.rb'
require_relative 'meraki/models/hardware_replacements_subtab_enum.rb'
require_relative 'meraki/models/sm_forums_enum.rb'
require_relative 'meraki/models/mode2_enum.rb'
require_relative 'meraki/models/v3_auth_mode_enum.rb'
require_relative 'meraki/models/v3_priv_mode_enum.rb'

# Exceptions
require_relative 'meraki/exceptions/api_exception.rb'

require_relative 'meraki/configuration.rb'

# Controllers
require_relative 'meraki/controllers/base_controller.rb'
require_relative 'meraki/controllers/api_usage_controller.rb'
require_relative 'meraki/controllers/action_batches_controller.rb'
require_relative 'meraki/controllers/admins_controller.rb'
require_relative 'meraki/controllers/alert_settings_controller.rb'
require_relative 'meraki/controllers/bluetooth_clients_controller.rb'
require_relative 'meraki/controllers/cameras_controller.rb'
require_relative 'meraki/controllers/clients_controller.rb'
require_relative 'meraki/controllers/config_templates_controller.rb'
require_relative 'meraki/controllers/content_filtering_categories_controller.rb'
require_relative 'meraki/controllers/content_filtering_rules_controller.rb'
require_relative 'meraki/controllers/dashboard_branding_policies_controller.rb'
require_relative 'meraki/controllers/devices_controller.rb'
require_relative 'meraki/controllers/firewalled_services_controller.rb'
require_relative 'meraki/controllers/group_policies_controller.rb'
require_relative 'meraki/controllers/http_servers_controller.rb'
require_relative 'meraki/controllers/intrusion_settings_controller.rb'
require_relative 'meraki/controllers/mrl3_firewall_controller.rb'
require_relative 'meraki/controllers/mv_sense_controller.rb'
require_relative 'meraki/controllers/mx11_nat_rules_controller.rb'
require_relative 'meraki/controllers/mx1_many_nat_rules_controller.rb'
require_relative 'meraki/controllers/mxl3_firewall_controller.rb'
require_relative 'meraki/controllers/mxl7_application_categories_controller.rb'
require_relative 'meraki/controllers/mxl7_firewall_controller.rb'
require_relative 'meraki/controllers/mxvlan_ports_controller.rb'
require_relative 'meraki/controllers/mxvpn_firewall_controller.rb'
require_relative 'meraki/controllers/mx_cellular_firewall_controller.rb'
require_relative 'meraki/controllers/mx_port_forwarding_rules_controller.rb'
require_relative 'meraki/controllers/mx_warm_spare_settings_controller.rb'
require_relative 'meraki/controllers/malware_settings_controller.rb'
require_relative 'meraki/controllers/management_interface_settings' \
                 '_controller.rb'
require_relative 'meraki/controllers/meraki_auth_users_controller.rb'
require_relative 'meraki/controllers/named_tag_scope_controller.rb'
require_relative 'meraki/controllers/netflow_settings_controller.rb'
require_relative 'meraki/controllers/networks_controller.rb'
require_relative 'meraki/controllers/open_api_spec_controller.rb'
require_relative 'meraki/controllers/organizations_controller.rb'
require_relative 'meraki/controllers/pii_controller.rb'
require_relative 'meraki/controllers/radio_settings_controller.rb'
require_relative 'meraki/controllers/saml_roles_controller.rb'
require_relative 'meraki/controllers/sm_controller.rb'
require_relative 'meraki/controllers/snmp_settings_controller.rb'
require_relative 'meraki/controllers/ssids_controller.rb'
require_relative 'meraki/controllers/security_events_controller.rb'
require_relative 'meraki/controllers/splash_login_attempts_controller.rb'
require_relative 'meraki/controllers/splash_settings_controller.rb'
require_relative 'meraki/controllers/static_routes_controller.rb'
require_relative 'meraki/controllers/switch_port_schedules_controller.rb'
require_relative 'meraki/controllers/switch_ports_controller.rb'
require_relative 'meraki/controllers/switch_profiles_controller.rb'
require_relative 'meraki/controllers/switch_settings_controller.rb'
require_relative 'meraki/controllers/switch_stacks_controller.rb'
require_relative 'meraki/controllers/syslog_servers_controller.rb'
require_relative 'meraki/controllers/traffic_analysis_settings_controller.rb'
require_relative 'meraki/controllers/traffic_shaping_controller.rb'
require_relative 'meraki/controllers/uplink_settings_controller.rb'
require_relative 'meraki/controllers/vlans_controller.rb'
require_relative 'meraki/controllers/webhook_logs_controller.rb'
require_relative 'meraki/controllers/wireless_health_controller.rb'
